### ISSUE TITLE
support layout

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/sitedown#6]
Right now sitedown is limited to a static header and footer. I've thought about adding basic layout support for a single file like

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>l1v3jRnL</title>
</head>
<body>
  {{content}}
</body>
</html>
```

or a more feature-rich setup like

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
</head>
<body>
  <header>
    <h1>{{title}}</h1>
    <nav>
      <ul>{{nav_links}}</ul>
    </nav>
  </header>

  <div class="markdown-body">
    {{content}}
  </div>

  <footer>
    <nav>
      <ul>{{nav_links}}</ul>
    </nav>
  </footer>
</body>
</html>
```

The first isn't too much of a stretch, but the second necessitates choosing a layout engine and allowing for some dynamic stuff that may be a bit beyond scope. @Flet feedback welcome

**Comment by ngoldman** [comment]
The interace would be something like

```
sitedown --layout layout.html
```

**Comment by ungoldman** [comment]
done in 2.0.0
